---
# Aesir
AesirRoleplayTask:
  custom_prompts:
  dataset_name: "aesir"
  filters:
    - ExactDedupFilter
# AI Dungeon
AiDungeonTextAdventureTask:
  custom_prompts:
  dataset_name: "aidungeon"
  filters:
    - ExactDedupFilter
    - SimilarityFilter
# Airoboros 1.4.1 - guess the instruction
Airoboros1GuessInstructionTask:
  custom_prompts:
  dataset_name: "airoboros"
  filters:
    - ExactDedupFilter
    - LlmSlopFilter
    - RefusalFilter
# Airoboros 1.4.1 - instruct
Airoboros1InstructionFollowingTask:
  custom_prompts:
  dataset_name: "airoboros"
  filters:
    - ExactDedupFilter
    - LlmSlopFilter
    - RefusalFilter
# AI Town
AiTownRoleplayTask:
  custom_prompts:
  dataset_name: "aitown"
  filters:
    - ExactDedupFilter
    - LlmSlopFilter
    - RefusalFilter
# Capybara
CapybaraInstructionFollowingTask:
  custom_prompts:
  dataset_name: "capybara"
  filters:
    - ExactDedupFilter
    - LlmSlopFilter
    - SimilarityFilter
# CAI
CharacterAiRoleplayTask:
  custom_prompts:
  dataset_name: "characterai"
  filters:
    - EnglishFilter
    - ExactDedupFilter
    - SimilarityFilter
  # If wanting only entries before Pyg-6B release, set to this: 1673398838000
  timestamp_cutoff: -1
ClaudeMultiroundInstructTask:
  custom_prompts:
  dataset_name: "claude-multiround"
  filters:
    - ExactDedupFilter
    - LlmSlopFilter
    - RefusalFilter
    - SimilarityFilter
# Club Floyd
ClubFloydTextAdventureTask:
  custom_prompts:
  dataset_name: "clubfloyd"
  filters:
    - ExactDedupFilter
    - SimilarityFilter
  min_user_rating: 3.0
# Dolly
DollyGuessInstructionTask:
  custom_prompts:
  dataset_name: "dolly"
  filters:
    - ExactDedupFilter
# Gemstruct
GemstructChatTask:
  capital_threshold: 0.5
  custom_prompts:
  dataset_name: "gemstruct"
  filters:
    - ExactDedupFilter
    - RefusalFilter
    - SimilarityFilter
  use_llama_outputs: false
# Small personal dataset
GoslingSetMixedPurposeTask:
  custom_prompts:
  dataset_name: "gosling"
  filters:
    - ExactDedupFilter
# LIMARP
LimaRpRoleplayTask:
  custom_prompts:
  dataset_name: "limarp"
  filters:
    - ExactDedupFilter
    - LowQualityRpFilter
    - SimilarityFilter
# Magnum
MagnumMixedPurposeTask:
  custom_prompts:
  dataset_name: "magnum"
  filters:
    - EnglishFilter
    - ExactDedupFilter
    - LlmSlopFilter
    - RefusalFilter
    - SimilarityFilter
  replace_claude_prompt: true
# MCStories
McStoriesWritingTask:
  custom_prompts:
  dataset_name: "mcstories"
  filters:
    - ExactDedupFilter
    - LowQualityRpFilter
    - SimilarityFilter
# no_robots - guess the instruction
NoRobotsGuessInstructionTask:
  custom_prompts:
  dataset_name: "no_robots"
  filters:
    - ExactDedupFilter
    - RefusalFilter
    - LlmSlopFilter
# no_robots - instruction following
NoRobotsInstructionFollowingTask:
  custom_prompts:
  dataset_name: "no_robots"
  filters:
    - ExactDedupFilter
    - RefusalFilter
    - LlmSlopFilter
    - SimilarityFilter
# OpenCAI
OpenCaiRoleplayTask:
  custom_prompts:
  dataset_name: "opencai"
  filters:
    - EnglishFilter
    - ExactDedupFilter
# Pyg-submitted Claude logs
PygClaudeRoleplayTask:
  custom_prompts:
  dataset_name: "pyg-claude"
  filters:
    - ExactDedupFilter
    - LlmSlopFilter
    - RefusalFilter
    - SimilarityFilter
# RP forums
RpForumsRoleplayTask:
  custom_prompts:
  dataset_name: "rpforums"
  filters:
    - ExactDedupFilter
    - LowQualityRpFilter
    - SimilarityFilter
  remove_ooc: true
# RP Guild
RpGuildRoleplayTask:
  custom_prompts:
  dataset_name: "rpguild"
  filters:
    - ExactDedupFilter
    - LowQualityRpFilter
    - SimilarityFilter
  remove_ooc: true
# SlimOrca
SlimOrcaInstructionFollowingTask:
  custom_prompts:
  dataset_name: "slimorca"
  filters:
    - ExactDedupFilter
    - RefusalFilter
    - LlmSlopFilter
  max_examples: 20000
# Teatime
TeatimeRoleplayTask:
  # Valid models: 'claude-v1-100k', 'gpt-3.5-turbo-0301', 'gpt-4-0314', 'claude-v1.2', 'claude-1.3-100k', 'claude-1.2', 'gpt-3.5-turbo-16k-0613'
  allowed_models:
    - claude-v1-100k
    - claude-v1.2
    - claude-1.3-100k
    - claude-1.2
  custom_prompts:
  dataset_name: "teatime"
  filters:
    - EnglishFilter
    - ExactDedupFilter
    - LlmSlopFilter
    - RefusalFilter
...
